In [32]:

#https://iamtrask.github.io/2015/07/12/basic-python-network/

import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        #return x*(1-x)
        return (1/(1+np.exp(-x)))*(1-(1/(1+np.exp(-x))))
    return 1/(1+np.exp(-x))

#RELU
#def nonlin(x,deriv=False):
##    if(deriv==True):
#        return 1/(1+np.exp(-x))
#    return np.log2(1+np.exp(x))

# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in xrange(10):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    #print iter
    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    print 'l1: ', l1
    print 'error: ', l1_error
    print 'sigmoid: ',nonlin(l1,True)
    print 'l1_delta: ', l1_delta
    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print "Output After Training:"
print l1


l1:  [[ 0.2689864 ]
 [ 0.36375058]
 [ 0.23762817]
 [ 0.3262757 ]]
error:  [[-0.2689864 ]
 [-0.36375058]
 [ 0.76237183]
 [ 0.6737243 ]]
sigmoid:  [[ 0.24553187]
 [ 0.24190935]
 [ 0.24650375]
 [ 0.24346281]]
l1_delta:  [[-0.06604473]
 [-0.08799467]
 [ 0.18792752]
 [ 0.16402681]]
l1:  [[ 0.30962857]
 [ 0.42918547]
 [ 0.35072407]
 [ 0.47522609]]
error:  [[-0.30962857]
 [-0.42918547]
 [ 0.64927593]
 [ 0.52477391]]
sigmoid:  [[ 0.24410259]
 [ 0.23883192]
 [ 0.24246695]
 [ 0.23639979]]
l1_delta:  [[-0.07558114]
 [-0.10250319]
 [ 0.15742795]
 [ 0.12405644]]
l1:  [[ 0.33215458]
 [ 0.46003   ]
 [ 0.44251197]
 [ 0.57621653]]
error:  [[-0.33215458]
 [-0.46003   ]
 [ 0.55748803]
 [ 0.42378347]]
sigmoid:  [[ 0.24322942]
 [ 0.23722619]
 [ 0.23815006]
 [ 0.23034498]]
l1_delta:  [[-0.08078977]
 [-0.10913116]
 [ 0.13276581]
 [ 0.0976164 ]]
l1:  [[ 0.34119015]
 [ 0.46722821]
 [ 0.50996617]
 [ 0.63797586]]
error:  [[-0.34119015]
 [-0.46722821]
 [ 0.49003383]
 [ 0.36202414]]
sigmoid:  [[ 0.2428632 ]
 [ 0.2

In [10]:
2*np.random.random((3,1))-1

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481]])

In [18]:
y, ':', nonlin(y)

(array([[0],
        [0],
        [1],
        [1]]), ':', array([[ 0.5       ],
        [ 0.5       ],
        [ 0.73105858],
        [ 0.73105858]]))

In [19]:
nonlin(y, True)

array([[0],
       [0],
       [0],
       [0]])

In [20]:
nonlin(np.dot(X,syn0))

array([[ 0.03176745],
       [ 0.02575143],
       [ 0.97907779],
       [ 0.97416005]])

## 3 layer network